[browser]
# タブのタイトルを設定
gatherUsageStats = false

[theme]
# テーマ設定
# primaryColor = "#FF6B6B"
primaryColor = "#cceecc"
backgroundColor = "#cceeee"
# backgroundColor = "#ffffff"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#7788bb" 
# textColor = "#262730" 